# Generated by Django 4.0.4 on 2022-05-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('state', models.CharField(choices=[('dr', 'Draft'), ('ac', 'Active'), ('dn', 'Done'), ('ar', 'Archived')], default='dr', max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
