# Generated by Django 4.0.4 on 2022-05-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Active'), (2, 'Done'), (3, 'Archived')], default=0),
        ),
    ]
